// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hooks$ReScriptUrql from "@urql/rescript/src/hooks/Hooks.bs.js";

var Raw = {};

var query = "query Identity  {\nme  {\nid  \ndisplayName  \n}\n\n}\n";

function parse(value) {
  var value$1 = value.me;
  return {
          me: !(value$1 == null) ? ({
                id: value$1.id,
                displayName: value$1.displayName
              }) : undefined
        };
}

function serialize(value) {
  var value$1 = value.me;
  var me;
  if (value$1 !== undefined) {
    var value$2 = value$1.displayName;
    var value$3 = value$1.id;
    me = {
      id: value$3,
      displayName: value$2
    };
  } else {
    me = null;
  }
  return {
          me: me
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var Definition = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables
};

function useQuery(param) {
  var match = Hooks$ReScriptUrql.useQuery({
        Raw: Raw,
        query: query,
        parse: parse,
        serializeVariables: serializeVariables,
        variablesToJson: (function (prim) {
            return prim;
          })
      }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  var full = match[0];
  return [
          full.response,
          full,
          match[1]
        ];
}

var Get = {
  Definition: Definition,
  useQuery: useQuery
};

var User = {
  Get: Get
};

function Main(Props) {
  var match = useQuery(undefined);
  var response = match[0];
  if (typeof response !== "number" && response.TAG === /* Data */0) {
    var me = response._0.me;
    if (me !== undefined) {
      return React.createElement("main", {
                  className: "text-red-500"
                }, me.displayName);
    }
    
  }
  return React.createElement("span", undefined, "Loading...");
}

var make = Main;

export {
  User ,
  make ,
  
}
/* react Not a pure module */
